# Generated by Django 2.0.13 on 2019-12-01 00:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_score', models.IntegerField()),
                ('question_content', models.TextField()),
                ('ans', models.CharField(choices=[('ONE', 'choice_one'), ('TWO', 'choice_two'), ('THR', 'choice_three'), ('FOU', 'choice_four'), ('FIV', 'choice_five')], default='ONE', max_length=20)),
                ('ox', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionNa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_score', models.IntegerField()),
                ('question_content', models.TextField()),
                ('ans1', models.CharField(max_length=200, null=True)),
                ('ans2', models.CharField(max_length=200, null=True)),
                ('ans3', models.CharField(max_length=200, null=True)),
                ('ans4', models.CharField(max_length=200, null=True)),
                ('ans5', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ox', models.BooleanField(default=False)),
                ('questionMc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.QuestionMc')),
                ('questionNa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.QuestionNa')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('test_time', models.DateTimeField(blank=True, null=True)),
                ('test_period', models.DurationField(choices=[(datetime.timedelta(seconds=3600), '1 hour'), (datetime.timedelta(seconds=10800), '3 hour'), (datetime.timedelta(seconds=18000), '5 hour')], default=datetime.timedelta(seconds=10800))),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auto_score', models.BooleanField(default=True)),
                ('total_score', models.IntegerField(null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_taken_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.Test'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionna',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.Test'),
        ),
        migrations.AddField(
            model_name='questionmc',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.Test'),
        ),
        migrations.AlterUniqueTogether(
            name='testeduser',
            unique_together={('user', 'test')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'test', 'questionNa'), ('user', 'test', 'questionMc')},
        ),
        migrations.AlterUniqueTogether(
            name='questionna',
            unique_together={('test', 'question_content')},
        ),
        migrations.AlterUniqueTogether(
            name='questionmc',
            unique_together={('test', 'question_content')},
        ),
    ]
