# Generated by Django 2.0.13 on 2019-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ctrlr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_time',
            field=models.DateTimeField(default=None),
        ),
    ]
