# Generated by Django 2.0.13 on 2019-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ctrlr', '0002_auto_20191201_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionna',
            old_name='ans1',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='questionna',
            old_name='ans2',
            new_name='std_ans',
        ),
        migrations.RemoveField(
            model_name='questionna',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='questionna',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='questionna',
            name='ans5',
        ),
        migrations.AddField(
            model_name='questionmc',
            name='std_ans',
            field=models.CharField(choices=[('ONE', 'choice_one'), ('TWO', 'choice_two'), ('THR', 'choice_three'), ('FOU', 'choice_four'), ('FIV', 'choice_five')], default='ONE', max_length=20),
        ),
    ]
