# Generated by Django 2.0.13 on 2019-12-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ctrlr', '0003_auto_20191201_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionna',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='admin_ctrlr.Test'),
        ),
    ]
