# Generated by Django 2.0.13 on 2019-12-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ctrlr', '0006_studentans_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentans',
            name='questionMc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.QuestionMc'),
        ),
        migrations.AddField(
            model_name='studentans',
            name='questionNa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_ctrlr.QuestionNa'),
        ),
    ]
