# Generated by Django 2.0.13 on 2019-12-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ctrlr', '0007_auto_20191205_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmc',
            old_name='ans',
            new_name='numofans',
        ),
        migrations.AddField(
            model_name='questionmc',
            name='ans1',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='questionmc',
            name='ans2',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='questionmc',
            name='ans3',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='questionmc',
            name='ans4',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionmc',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mcquests', to='admin_ctrlr.Test'),
        ),
        migrations.AlterField(
            model_name='questionna',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Naquests', to='admin_ctrlr.Test'),
        ),
    ]
