# Generated by Django 2.0.13 on 2019-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ctrlr', '0008_auto_20191206_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmc',
            old_name='numofans',
            new_name='cor_ans',
        ),
        migrations.RemoveField(
            model_name='questionmc',
            name='ox',
        ),
        migrations.AddField(
            model_name='questionmc',
            name='ans5',
            field=models.CharField(default='보기를 입력하세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionmc',
            name='ans1',
            field=models.CharField(default='보기를 입력하세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionmc',
            name='ans2',
            field=models.CharField(default='보기를 입력하세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionmc',
            name='ans3',
            field=models.CharField(default='보기를 입력하세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionmc',
            name='ans4',
            field=models.CharField(default='보기를 입력하세요', max_length=20),
        ),
    ]
