# Generated by Django 2.0.13 on 2019-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ctrlr', '0010_auto_20191208_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_time',
            field=models.DateField(default=None),
        ),
    ]
