# Generated by Django 2.0.13 on 2019-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
