# Generated by Django 2.0.13 on 2019-12-05 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
